### PR TITLE
replace react context by valtio

### PR DESCRIPTION
**Pull request by SamueleA**
TODO: add valtio for kit checkout

### CODE REVIEW

**Comment by pkieltyka** [comment]
please lets not add valito..

**Comment by SamueleA** [comment]
> please lets not add valito..

What are the reasons for not using Valtio?
Currently, we're doing state management with React Context only. Valtio would simplify how we're doing state management.

**Comment by pkieltyka** [comment]
my hope is we can keep sequence kit very lean. but I think it would be fine if we used it on some subpackages.. I will defer to @corbanbrook what he wants to do

**Comment by corbanbrook** [comment]
Im not against valtio, we use it successfully in other projects (market-app) and people seem to like it. Its rather small, similar in size to most other state management libs. I do respect that we want to avoid adding any unnecessary bloat, and we have a working solution with React primitives (context, useState), but as applications get more complicated its generally thought that the react primitives fall a little flat and easier DX with other state management libs.

**Pull request closed without merging**
